### PR TITLE
 New UI Design

### PR DESCRIPTION
**Pull request by Maximiliano-Santana**
Aplicar configuración de esquema de colores, tema al sitio, assets y botones.

### CODE REVIEW

**Review by kittybest — COMMENTED** [review]
question: should this be merged to main? I think we should have an independent branch for ETH Mexico?

**Comment by 0xmad** [comment]
Sorry, this PR won't be a part for maci-rpgf because it's related only to ETH Mexico.

**Review by Mapuppy09 — COMMENTED** [review]
I AM NOT UNDESRSTAND THE NEXT STEP AND THIS INFORMATION TO SENT TO ACRA , PLEASE LET ME KNOW , WHAT I DOING?

**Comment by kittybest** [comment]
> I AM NOT UNDESRSTAND THE NEXT STEP AND THIS INFORMATION TO SENT TO ACRA , PLEASE LET ME KNOW , WHAT I DOING?

maybe we could open a branch especially for ETH mexico and for this PR to be merged to? how do you think @0xmad ?

**Comment by 0xmad** [comment]
@kittybest I think it can live in ETH Mexico fork, I don't see any reason to create a branch for it.

**Comment by ccolorado** [comment]
Sorry, we Sent a pr to the wrong repo. Please ignore

**Comment by Mapuppy09** [comment]
Ok , not problem .

Mayra delapaz

**Pull request closed without merging**
